// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK4pNwvpq3D7jsj72MAPVDkuDdiU4nS6Y',
    appId: '1:931006881329:web:bfdf99e343b423e678ff10',
    messagingSenderId: '931006881329',
    projectId: 'greener-storage',
    authDomain: 'greener-storage.firebaseapp.com',
    storageBucket: 'greener-storage.appspot.com',
    databaseURL: 'https://greener-storage-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbiTty3pkLEZNMxFUMbRetPiBv_KiE-s',
    appId: '1:931006881329:android:3a905cd0dcb9cbf278ff10',
    messagingSenderId: '931006881329',
    projectId: 'greener-storage',
    storageBucket: 'greener-storage.appspot.com',
    databaseURL: 'https://greener-storage-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-jvvvuMDO5x9TaW6RB93LI6KGWTeu2CY',
    appId: '1:931006881329:ios:19b5867b1113df8978ff10',
    messagingSenderId: '931006881329',
    projectId: 'greener-storage',
    storageBucket: 'greener-storage.appspot.com',
    iosBundleId: 'com.example.greener',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-jvvvuMDO5x9TaW6RB93LI6KGWTeu2CY',
    appId: '1:931006881329:ios:19b5867b1113df8978ff10',
    messagingSenderId: '931006881329',
    projectId: 'greener-storage',
    storageBucket: 'greener-storage.appspot.com',
    iosBundleId: 'com.example.greener',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK4pNwvpq3D7jsj72MAPVDkuDdiU4nS6Y',
    appId: '1:931006881329:web:9c3eefdeb282331a78ff10',
    messagingSenderId: '931006881329',
    projectId: 'greener-storage',
    authDomain: 'greener-storage.firebaseapp.com',
    storageBucket: 'greener-storage.appspot.com',
  );
}
